version: "3.8"

services:
  mongo:
    image: mongo:latest
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - ./database/db:/data/db
    networks:
      - lognet

  api:
    container_name: api
    restart: always
    build: ./backend
    environment:
      MONGO_URI: *your-mongo-uri*
      MY_EMAIL_ADDR: *your-email-address*
      MY_EMAIL_PASS: *your-email's-password*
      SECRET: *64-bit-hash-key*
    ports:
      - 4000:4000
    networks:
      - lognet

  seed:
    container_name: seed
    build: ./seed
    depends_on:
      - mongo
    networks:
      - lognet

  client:
    container_name: client
    build: ./frontend
    ports:
      - 3000:3000
    depends_on:
      - api
    networks:
      - lognet

  mongo-express:
    image: mongo-express
    restart: unless-stopped
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_URL: mongodb://root:example@mongo:27017/
    depends_on:
      - mongo
    networks:
      - lognet

networks:
  lognet:
    driver: bridge
