POST http://localhost:4000/api/tickets/add-ticket
Content-Type: application/json

{
    "full_name":"oryan", 
    "movie_id":"dhwbchjds", 
    "email":"oryan@gmail.com", 
    "movie_title":"titla", 
    "sit": "8c", 
    "price": 49, 
    "movie_date": "1/2/33", 
    "time_start": "08:00"
}

###
GET http://localhost:4000/api/tickets/view-tickets