POST http://localhost:4000/api/tickets/add-ticket
Content-Type: application/json

{
    "full_name":"oryan", 
    "movie_id":"dhwbchjds", 
    "email":"oryan@gmail.com", 
    "movie_title":"titla", 
    "sit": "8c", 
    "price": 49, 
    "movie_date": "1/2/33", 
    "time_start": "08:00"
}

# MOVIE ROUTES
###
POST http://localhost:4000/api/movies/add-movie
Content-Type: application/json

{
    "movie_title": "title1", 
    "img": "img1", 
    "trailer": "trailer1", 
    "ganres": ["comedy"], 
    "description": "description1", 
    "price": 68, 
    "movie_date": "01/12/22", 
    "time_start": "18:00"
}

###
GET http://localhost:4000/api/movies/get-movies

###
GET http://localhost:4000/api/movies/details/89e441b8-98ca-4456-91e9-180b1d1fefa3

###
DELETE http://localhost:4000/api/movies/delete-movie/c9b8de54-3506-4f7f-9999-6415ee587af3

# Tickets ROUTES
###
POST http://localhost:4000/api/tickets/get-verification
Content-Type: application/json

{
    "full_name":"oryan abergel", 
    "email":"oryan445@gmail.com",
    "age": 18
}

###
POST http://localhost:4000/api/tickets/verify
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsX25hbWUiOiJvcnlhbiBhYmVyZ2VsIiwiZW1haWwiOiJvcnlhbjQ0NUBnbWFpbC5jb20iLCJpYXQiOjE2NDM1NzAwODksImV4cCI6MTY0MzU3MTg4OX0.0OfCZdlxCeLed9agPSZimTebBmxS82IiF1e5_yqN760
Content-Type: application/json

{
    "full_name":"oryan abergel", 
    "email":"oryan445@gmail.com"
}

###
POST http://localhost:4000/api/tickets/purchase-ticket
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJmdWxsX25hbWUiOiJvcnlhbiBhYmVyZ2VsIiwiZW1haWwiOiJvcnlhbjQ0NUBnbWFpbC5jb20iLCJpYXQiOjE2NDM1NzAwODksImV4cCI6MTY0MzU3MTg4OX0.0OfCZdlxCeLed9agPSZimTebBmxS82IiF1e5_yqN760
Content-Type: application/json

{
    "full_name":"oryan abergel", 
    "movie_id":"89e441b8-98ca-4456-91e9-180b1d1fefa3", 
    "email":"oryan445@gmail.com", 
    "movie_title":"title1", 
    "seats": ["8c"], 
    "price": 49, 
    "movie_date": "1/2/33", 
    "time_start": "08:00",
    "card_number":"2222333344445555", 
    "card_expiration_date":"1/02/23", 
    "national_id":"207344430", 
    "ccv":"929"
}

###
GET http://localhost:4000/api/tickets/view-tickets

###
GET http://localhost:4000/api/tickets/view-ticket-details/:orderId

###
PUT http://localhost:4000/api/tickets/change-seat
Authorization: Bearer token
Content-Type: application/json

{
    "movieId":"89e441b8-98ca-4456-91e9-180b1d1fefa3", 
    "email":"", 
    "seats":[""], 
    "orderId":""
}

